version: "3.8"
services:
  dcmpl:
    container_name: "dcmpl"
    image: "dcmpl:latest"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/workspace
    ports:
      - 6006:6006
    network_mode: host
    command: "tensorboard --logdir saved/log/"